web_services = {
    'planetary/apod': 'date'
    ,'neo/rest/v1/feed': 'date'
    ,'DONKI/CME': 'activityID'
    ,'DONKI/CMEAnalysis': 'associatedCMEID'
    ,'DONKI/GST': 'gstID'
    ,'DONKI/HSS': 'hssID'
    ,'DONKI/IPS': 'activityID'
    ,'DONKI/MPC': 'mpcID'
    ,'DONKI/notifications': 'messageID'
    ,'DONKI/RBE': 'rbeID'
    ,'DONKI/SEP': 'sepID'
    # ,'DONKI/WSAEnlilSimulations': 'simulationID'
    # ,'EPIC/api/natural/date/': 'identifier'
    # ,'EPIC/api/enhanced/date/': 'identifier'
    # ,'mars-photos/api/v1/rovers/perseverance/photos': 'id'
    # ,'mars-photos/api/v1/rovers/curiosity/photos': 'id'
    # ,'mars-photos/api/v1/rovers/opportunity/photos': 'id'
    # ,'mars-photos/api/v1/rovers/spirit/photos': 'id'
    # ,'planetary/earth/assets': 'id'
}